add clippy to the pre-commit hook

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,5 +1,13 @@
 #!/bin/sh
 set -e
 cargo fmt --all > /dev/null 2>&1
+
+cargo clippy -- -D warnings
+
+if [ $? -ne 0 ]; then
+    echo "Clippy failed, commit aborted"
+    exit 1
+fi
+
 git diff --quiet || git add -u
 exit 0
